[build]
  # This tells Netlify where the code lives
  base = "finsent/frontend"
  
  # This tells Netlify where the build output is
  # Note: Next.js Runtime v5 handles this best when set simply to .next
  publish = ".next"
  
  # The build command to run inside that base directory
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"
